personal-library-api: jdbc, db
delacroix23/personal-library-api pull request #1
Opened 2020-09-04 08:42 UTC by irynarogoza

2020-09-04 19:32 UTC, delacroix23 requested changes

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/config/JdbcConfig.java
> +@ComponentScan("com.baeldung.jdbc")
remove this line

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/config/JdbcConfig.java
> +        dataSource.setDriverClassName("com.mysql.jdbc.Driver");
replace driver class name as it deprecated on com.mysql.cj.jdbc.Driver (see application log)

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/config/RestTemplateConfig.java
> +}
add new line) optional

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/dto/Contributor.java
> +public class Contributor {
better to have descending order but it more up on taste 
@Data
@NoArgsConstructor
@AllArgsConstructor

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private Integer number_of_pages;
as for training in complex dto construction this class is ok, but main idea in such tasks is to get only necessary fields which will be used, hence all redundant should be removed as they increasing complexity without value for logic

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    private static final String ISBN_ENDPOINT = "https://openlibrary.org/api/books";
This value of variable should be moved to application.properties and injected as value

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    //https://openlibrary.org/api/books?bibkeys=ISBN:9780980200447&jscmd=details&format=json
This line should be removed, no any non informative comments in the code)))

2020-09-04 19:32 UTC, delacroix23 commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +        return ISBN_ENDPOINT + "?bibkeys=ISBN:" + isbnCode + "&jscmd=details&format=json";
add logging of call on debug level

2020-09-04 20:06 UTC, irynarogoza commented on pom.xml
> +            <version>8.0.21</version>
fixed

2020-09-04 20:07 UTC, irynarogoza commented on pom.xml
> +    <!--<packaging>war</packaging>-->
fixed

2020-09-04 20:07 UTC, irynarogoza commented on pom.xml
> +                <artifactId>spring-boot-maven-plugin</artifactId>
fixed

2020-09-04 20:07 UTC, irynarogoza commented on src/main/java/com/education/library/config/JdbcConfig.java
> +@ComponentScan("com.baeldung.jdbc")
fixed

2020-09-04 20:08 UTC, irynarogoza commented on src/main/java/com/education/library/config/JdbcConfig.java
> +        dataSource.setDriverClassName("com.mysql.jdbc.Driver");
fixed

2020-09-04 20:12 UTC, irynarogoza commented on src/main/java/com/education/library/dto/Contributor.java
> +public class Contributor {
fixed

2020-09-04 20:15 UTC, irynarogoza commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private Integer number_of_pages;
fixed

2020-09-04 20:16 UTC, irynarogoza commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    //https://openlibrary.org/api/books?bibkeys=ISBN:9780980200447&jscmd=details&format=json
fixed

2020-09-04 20:49 UTC, irynarogoza commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    private static final String ISBN_ENDPOINT = "https://openlibrary.org/api/books";
fixed

2020-09-05 06:58 UTC, delacroix23 requested changes

2020-09-05 06:58 UTC, delacroix23 commented on src/main/java/com/education/library/dto/Isbn.java
> +    private String info_url;
Camel case style for field names

2020-09-05 06:58 UTC, delacroix23 commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private List<Integer> isbn_10;
Camel case

2020-09-05 06:58 UTC, delacroix23 commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    private String isbn_url;
By code convention we use for static variable **UPPER_CASE_WITH_UNDERSCORE**, for all other fields and variables **camelCaseStyle**

2020-09-05 06:58 UTC, delacroix23 commented on src/main/resources/propertyfiles/application.properties
> +ISBN_ENDPOINT=https://openlibrary.org/api/books
it is not common way to define property with **UPPER_CASE_WITH_UNDERSCORE** please see example in article which you have read https://dev-gang.ru/article/spring-value-annotacija-v08ja8ki2x/

2020-09-05 07:15 UTC, irynarogoza commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private List<Integer> isbn_10;
fixed

2020-09-05 07:17 UTC, irynarogoza commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +        return ISBN_ENDPOINT + "?bibkeys=ISBN:" + isbnCode + "&jscmd=details&format=json";
fixed

2020-09-05 07:17 UTC, irynarogoza commented on src/main/java/com/education/library/dto/Isbn.java
> +    private String info_url;
fixed

2020-09-05 07:17 UTC, irynarogoza commented on src/main/java/com/education/library/service/OpenLibraryService.java
> +    private String isbn_url;
fixed

2020-09-05 07:17 UTC, irynarogoza commented on src/main/resources/propertyfiles/application.properties
> +ISBN_ENDPOINT=https://openlibrary.org/api/books
fixed

2020-09-05 07:35 UTC, delacroix23 requested changes

2020-09-05 07:35 UTC, delacroix23 commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private List<String> isbn13;
just to let you know here the name of variable could not match original key which you stated in @JsonProperty

2020-09-05 07:35 UTC, delacroix23 commented on src/main/java/com/education/library/dto/IsbnDetails.java
> +    private List<Integer> isbn_10;
line 23

2020-09-05 07:42 UTC, delacroix23 approved these changes

2020-09-05 07:42 UTC, merged